#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x0e,0x27,0x36,0x5a,0x24,0xd9,
};

static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0x0e,0x27,0x36,0x5a,0x4b,0xeb,
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H